# Generated by Django 6.0 on 2026-01-09 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("art_no", models.CharField(db_index=True, max_length=50)),
                (
                    "art_supplier",
                    models.CharField(
                        choices=[("OKB", "OKB"), ("SW", "SW"), ("RKB", "RKB")],
                        db_index=True,
                        default="OKB",
                        help_text="Das ist der Lieferant des Artikels.",
                        verbose_name="Artikel Lieferant",
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_no",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("art_no", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="Der Status der Bestellung (0=offen, 1=abgeschlossen).",
                        verbose_name="Status",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "tag_id",
                    models.CharField(
                        db_index=True, max_length=24, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        default=0,
                        help_text="Der Status der Kanban Box (0=leer, 1=voll).",
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "art_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.article"
                    ),
                ),
            ],
        ),
    ]
