# Generated by Django 6.0 on 2025-12-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="art_no",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="article",
            name="art_supplier",
            field=models.CharField(
                choices=[("OKB", "OKB"), ("SW", "SW"), ("RKB", "RKB")],
                db_index=True,
                default="OKB",
                help_text="Das ist der Lieferant des Artikels.",
                verbose_name="Artikel Lieferant",
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="tag_id",
            field=models.CharField(db_index=True, max_length=24, unique=True),
        ),
    ]
