{{- if eq .Values.application.environment "prod" }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: kanbanapi-prod
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - k8s.otec.de
        - "*.k8s.otec.de"
      secretName: cert-k8s.otec.de
  rules:
    - host: kanbanapi.k8s.otec.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
{{- else }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: kanbanapi-test
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - k8s.otec.de
        - '*.k8s.otec.de'
      secretName: cert-k8s.otec.de
  rules:
    - host: kanbanapi-test.k8s.otec.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80
{{- end }}